### ISSUE TITLE
Hello, how can this program be used for conventional VTI FWI?

### ISSUE THREAD

**Issue by StarrMoonn** [nmbader/fwi2d#1]
Hello, I am very interested in your project. In the examples provided, DAS data modeling is used. If I want to model a conventional VTI anisotropic medium, how should I adjust the relevant parameters? Additionally, I noticed that the elastic wave FWI example involves an isotropic medium. Is there a complete FWI example that includes Thomsen parameters?

**Comment by Nuoyan-JLU** [comment]
# load, and plot
axes_data, data = sep.read_file(datapath+"elastic_data.H")
edata = data.reshape(axes_data.n,order='F').T
edata=np.reshape(edata,(2,2,5,nt)) # 2 shots, 2 components, 5 receivers, nt time samples

when I ”plt.imshow(np.transpose(edata[:,:]),interpolation='bilinear',aspect="auto",cmap='Greys')“，there is an issue where `edata` is a four-dimensional array, which prevents it from being plotted directly. However, the example `dasdata` can be plotted without any issues. Does this indicate that the code is incomplete or not well-designed?
